import type { ExperienceLevel } from "./types";

export const DAILY_TARGET = 40;
export const MATCH_THRESHOLD = 55;
export const GEMINI_SHORTLIST = 80;
export const QUEUE_SIZE = 40;

export const INDIA_CITIES = [
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Chennai",
  "Gurugram",
  "Noida",
  "Delhi",
  "NCR",
  "Ahmedabad",
  "Kolkata",
  "Jaipur",
  "Kochi",
  "Coimbatore",
  "Chandigarh",
  "Remote India",
] as const;

export const INDIA_LOCATION_HINTS = [
  "india",
  "bharat",
  "bengaluru",
  "bangalore",
  "hyderabad",
  "pune",
  "mumbai",
  "chennai",
  "gurugram",
  "gurgaon",
  "noida",
  "delhi",
  "ncr",
  "ahmedabad",
  "kolkata",
  "jaipur",
  "kochi",
  "coimbatore",
  "chandigarh",
  "karnataka",
  "telangana",
  "maharashtra",
  "tamil nadu",
  "haryana",
  "remote - india",
  "remote, india",
  "remote india",
  "work from india",
];

export const LEVEL_LABELS: Record<ExperienceLevel, string> = {
  fresher: "Fresher / campus",
  junior: "Junior (0–2 yrs)",
  mid: "Mid (2–5 yrs)",
  senior: "Senior (5–8 yrs)",
  lead: "Lead / staff (8+ yrs)",
};

export const LEVEL_TITLE_HINTS: Record<ExperienceLevel, string[]> = {
  fresher: [
    "intern",
    "internship",
    "fresher",
    "graduate",
    "trainee",
    "campus",
    "entry level",
    "entry-level",
    "apprentice",
  ],
  junior: [
    "junior",
    "associate",
    "sde-1",
    "sde 1",
    "sde i",
    "sde1",
    "engineer i",
    "engineer 1",
    "l1",
    "ic1",
  ],
  mid: [
    "sde-2",
    "sde 2",
    "sde ii",
    "sde2",
    "engineer ii",
    "engineer 2",
    "mid-level",
    "mid level",
    "intermediate",
    "l2",
    "ic2",
  ],
  senior: [
    "senior",
    "sr.",
    "sr ",
    "sde-3",
    "sde 3",
    "sde iii",
    "sde3",
    "engineer iii",
    "l3",
    "ic3",
  ],
  lead: [
    "lead",
    "staff",
    "principal",
    "manager",
    "architect",
    "head of",
    "director",
    "sde-4",
    "l4",
    "l5",
    "ic4",
    "ic5",
  ],
};
