import type { ExperienceLevel } from "./types";

export const DAILY_TARGET = 40;
export const MATCH_THRESHOLD = 55;
export const GEMINI_SHORTLIST = 80;
export const QUEUE_SIZE = 40;

export const FOCUS_CITIES = ["Bengaluru", "Hyderabad", "Chennai"] as const;

export const CITY_ALIASES: Record<string, string[]> = {
  bengaluru: ["bengaluru", "bangalore", "blr"],
  hyderabad: ["hyderabad"],
  chennai: ["chennai", "madras"],
  pune: ["pune"],
  mumbai: ["mumbai", "bombay"],
  gurugram: ["gurugram", "gurgaon"],
  noida: ["noida"],
  delhi: ["delhi", "new delhi"],
  ncr: ["ncr", "delhi ncr"],
  ahmedabad: ["ahmedabad"],
  kolkata: ["kolkata", "calcutta"],
  jaipur: ["jaipur"],
  kochi: ["kochi", "cochin"],
  coimbatore: ["coimbatore"],
  chandigarh: ["chandigarh"],
};

export const INDIA_EMPLOYERS = [
  "Capgemini",
  "Accenture",
  "Cognizant",
  "TCS",
  "Infosys",
  "Wipro",
  "HCLTech",
  "Tech Mahindra",
  "IBM",
  "Oracle",
  "Deloitte",
  "Amazon",
  "Microsoft",
  "Google",
  "JPMorgan",
  "Goldman Sachs",
  "Wells Fargo",
  "Optum",
  "Bosch",
  "Honeywell",
  "SAP",
  "Cisco",
  "Zoho",
  "Thoughtworks",
  "Persistent",
  "Mphasis",
  "LTIMindtree",
  "Coforge",
  "Hexaware",
  "Nagarro",
  "Fractal",
  "Flipkart",
  "Swiggy",
  "Razorpay",
  "PhonePe",
  "Freshworks",
  "Atlassian",
  "Qualcomm",
  "Intel",
  "Adobe",
  "Uber",
  "Target",
  "Walmart",
  "Barclays",
  "HSBC",
  "Standard Chartered",
  "Publicis Sapient",
];

export const FOREIGN_LOCATION_MARKERS = [
  "united kingdom",
  "united states",
  "u.s.",
  "u.k.",
  "london",
  "manchester",
  "ireland",
  "dublin",
  "germany",
  "berlin",
  "munich",
  "france",
  "paris",
  "netherlands",
  "amsterdam",
  "singapore",
  "australia",
  "sydney",
  "melbourne",
  "canada",
  "toronto",
  "vancouver",
  "poland",
  "warsaw",
  "japan",
  "tokyo",
  "brazil",
  "mexico",
  "spain",
  "madrid",
  "italy",
  "sweden",
  "norway",
  "denmark",
  "finland",
  "switzerland",
  "zurich",
  "dubai",
  "abu dhabi",
  "israel",
  "tel aviv",
  "china",
  "hong kong",
  "taiwan",
  "south korea",
  "seoul",
  "south africa",
  "new york",
  "san francisco",
  "seattle",
  "austin",
  "boston",
  "chicago",
  "california",
  "indianapolis",
  "united arab",
];

export const INDIA_CITIES = [
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Mumbai",
  "Chennai",
  "Gurugram",
  "Noida",
  "Delhi",
  "NCR",
  "Ahmedabad",
  "Kolkata",
  "Jaipur",
  "Kochi",
  "Coimbatore",
  "Chandigarh",
  "Remote India",
] as const;

export const INDIA_LOCATION_HINTS = [
  "india",
  "bharat",
  "bengaluru",
  "bangalore",
  "hyderabad",
  "pune",
  "mumbai",
  "chennai",
  "gurugram",
  "gurgaon",
  "noida",
  "delhi",
  "ncr",
  "ahmedabad",
  "kolkata",
  "jaipur",
  "kochi",
  "coimbatore",
  "chandigarh",
  "karnataka",
  "telangana",
  "maharashtra",
  "tamil nadu",
  "haryana",
  "remote - india",
  "remote, india",
  "remote india",
  "work from india",
];

export const LEVEL_LABELS: Record<ExperienceLevel, string> = {
  fresher: "Fresher / campus",
  junior: "Junior (0–2 yrs)",
  mid: "Mid (2–5 yrs)",
  senior: "Senior (5–8 yrs)",
  lead: "Lead / staff (8+ yrs)",
};

export const LEVEL_TITLE_HINTS: Record<ExperienceLevel, string[]> = {
  fresher: [
    "intern",
    "internship",
    "fresher",
    "graduate",
    "trainee",
    "campus",
    "entry level",
    "entry-level",
    "apprentice",
  ],
  junior: [
    "junior",
    "associate",
    "sde-1",
    "sde 1",
    "sde i",
    "sde1",
    "engineer i",
    "engineer 1",
    "l1",
    "ic1",
  ],
  mid: [
    "sde-2",
    "sde 2",
    "sde ii",
    "sde2",
    "engineer ii",
    "engineer 2",
    "mid-level",
    "mid level",
    "intermediate",
    "l2",
    "ic2",
  ],
  senior: [
    "senior",
    "sr.",
    "sr ",
    "sde-3",
    "sde 3",
    "sde iii",
    "sde3",
    "engineer iii",
    "l3",
    "ic3",
  ],
  lead: [
    "lead",
    "staff",
    "principal",
    "manager",
    "architect",
    "head of",
    "director",
    "sde-4",
    "l4",
    "l5",
    "ic4",
    "ic5",
  ],
};
