export type AtsKind = "greenhouse" | "lever" | "ashby" | "workable";

export interface AtsCompany {
  name: string;
  slug: string;
  kind: AtsKind;
}

/** Public career-board slugs for companies that hire in India or allow India remote. Wrong slugs fail quietly. */
export const ATS_COMPANIES: AtsCompany[] = [
  { name: "Postman", slug: "postman", kind: "greenhouse" },
  { name: "BrowserStack", slug: "browserstack", kind: "greenhouse" },
  { name: "Chargebee", slug: "chargebee", kind: "greenhouse" },
  { name: "Freshworks", slug: "freshworks", kind: "greenhouse" },
  { name: "Whatfix", slug: "whatfix", kind: "greenhouse" },
  { name: "LambdaTest", slug: "lambdatest", kind: "greenhouse" },
  { name: "Druva", slug: "druva", kind: "greenhouse" },
  { name: "Innovaccer", slug: "innovaccer", kind: "greenhouse" },
  { name: "Groww", slug: "groww", kind: "greenhouse" },
  { name: "Meesho", slug: "meesho", kind: "greenhouse" },
  { name: "Swiggy", slug: "swiggy", kind: "greenhouse" },
  { name: "Flipkart", slug: "flipkart", kind: "greenhouse" },
  { name: "Atlassian", slug: "atlassian", kind: "greenhouse" },
  { name: "Stripe", slug: "stripe", kind: "greenhouse" },
  { name: "Cloudflare", slug: "cloudflare", kind: "greenhouse" },
  { name: "Databricks", slug: "databricks", kind: "greenhouse" },
  { name: "MongoDB", slug: "mongodb", kind: "greenhouse" },
  { name: "Elastic", slug: "elastic", kind: "greenhouse" },
  { name: "Twilio", slug: "twilio", kind: "greenhouse" },
  { name: "Okta", slug: "okta", kind: "greenhouse" },
  { name: "Snowflake", slug: "snowflake", kind: "greenhouse" },
  { name: "Datadog", slug: "datadog", kind: "greenhouse" },
  { name: "Cloudinary", slug: "cloudinary", kind: "greenhouse" },
  { name: "HashiCorp", slug: "hashicorp", kind: "greenhouse" },
  { name: "GitLab", slug: "gitlab", kind: "greenhouse" },
  { name: "Figma", slug: "figma", kind: "greenhouse" },
  { name: "Notion", slug: "notion", kind: "greenhouse" },
  { name: "Airbnb", slug: "airbnb", kind: "greenhouse" },
  { name: "Uber", slug: "uber", kind: "greenhouse" },
  { name: "Spotify", slug: "spotify", kind: "greenhouse" },
  { name: "Adobe", slug: "adobe", kind: "greenhouse" },
  { name: "Nvidia", slug: "nvidia", kind: "greenhouse" },
  { name: "Intel", slug: "intel", kind: "greenhouse" },
  { name: "Qualcomm", slug: "qualcomm", kind: "greenhouse" },
  { name: "HubSpot", slug: "hubspot", kind: "greenhouse" },
  { name: "Zendesk", slug: "zendesk", kind: "greenhouse" },
  { name: "Asana", slug: "asana", kind: "greenhouse" },
  { name: "Dropbox", slug: "dropbox", kind: "greenhouse" },
  { name: "Box", slug: "boxinc", kind: "greenhouse" },
  { name: "DocuSign", slug: "docusign", kind: "greenhouse" },
  { name: "Pinterest", slug: "pinterest", kind: "greenhouse" },
  { name: "Reddit", slug: "reddit", kind: "greenhouse" },
  { name: "Discord", slug: "discord", kind: "greenhouse" },
  { name: "Airtable", slug: "airtable", kind: "greenhouse" },
  { name: "Amplitude", slug: "amplitude", kind: "greenhouse" },
  { name: "Braze", slug: "braze", kind: "greenhouse" },
  { name: "Mixpanel", slug: "mixpanel", kind: "greenhouse" },
  { name: "Clerk", slug: "clerk", kind: "greenhouse" },
  { name: "Grammarly", slug: "grammarly", kind: "greenhouse" },
  { name: "Coursera", slug: "coursera", kind: "greenhouse" },
  { name: "Duolingo", slug: "duolingo", kind: "greenhouse" },
  { name: "Razorpay", slug: "razorpay", kind: "lever" },
  { name: "CRED", slug: "cred", kind: "lever" },
  { name: "PhonePe", slug: "phonepe", kind: "lever" },
  { name: "Dream11", slug: "dream11", kind: "lever" },
  { name: "Unacademy", slug: "unacademy", kind: "lever" },
  { name: "Vedantu", slug: "vedantu", kind: "lever" },
  { name: "Apna", slug: "apna", kind: "lever" },
  { name: "Slice", slug: "slice", kind: "lever" },
  { name: "Jupiter", slug: "jupiter", kind: "lever" },
  { name: "FamPay", slug: "fampay", kind: "lever" },
  { name: "Smallcase", slug: "smallcase", kind: "lever" },
  { name: "Upstox", slug: "upstox", kind: "lever" },
  { name: "CoinDCX", slug: "coindcx", kind: "lever" },
  { name: "Delhivery", slug: "delhivery", kind: "lever" },
  { name: "Licious", slug: "licious", kind: "lever" },
  { name: "Zepto", slug: "zepto", kind: "lever" },
  { name: "Blinkit", slug: "blinkit", kind: "lever" },
  { name: "Urban Company", slug: "urbancompany", kind: "lever" },
  { name: "OkCredit", slug: "okcredit", kind: "lever" },
  { name: "Yellow", slug: "yellow", kind: "lever" },
  { name: "Canva", slug: "canva", kind: "lever" },
  { name: "Netflix", slug: "netflix", kind: "lever" },
  { name: "Palantir", slug: "palantir", kind: "lever" },
  { name: "Shopify", slug: "shopify", kind: "lever" },
  { name: "Twitch", slug: "twitch", kind: "lever" },
  { name: "Vercel", slug: "vercel", kind: "ashby" },
  { name: "Linear", slug: "linear", kind: "ashby" },
  { name: "OpenAI", slug: "openai", kind: "ashby" },
  { name: "Anthropic", slug: "anthropic", kind: "ashby" },
  { name: "Ramp", slug: "ramp", kind: "ashby" },
  { name: "Mercury", slug: "mercury", kind: "ashby" },
  { name: "Perplexity", slug: "perplexity", kind: "ashby" },
  { name: "Supabase", slug: "supabase", kind: "ashby" },
  { name: "Neon", slug: "neon", kind: "ashby" },
  { name: "PlanetScale", slug: "planetscale", kind: "ashby" },
  { name: "Railway", slug: "railway", kind: "ashby" },
  { name: "Render", slug: "render", kind: "ashby" },
  { name: "Rippling", slug: "rippling", kind: "ashby" },
  { name: "Notion Ashby", slug: "notion", kind: "ashby" },
  { name: "Cursor", slug: "cursor", kind: "ashby" },
  { name: "BrowserStack Workable", slug: "browserstack", kind: "workable" },
  { name: "Thoughtworks", slug: "thoughtworks", kind: "workable" },
  { name: "Persistent", slug: "persistent", kind: "workable" },
  { name: "Mphasis", slug: "mphasis", kind: "workable" },
  { name: "LTIMindtree", slug: "ltimindtree", kind: "workable" },
  { name: "Coforge", slug: "coforge", kind: "workable" },
  { name: "Hexaware", slug: "hexaware", kind: "workable" },
  { name: "Birlasoft", slug: "birlasoft", kind: "workable" },
];
